src/components/myPageComponent/MyPageContents.jsx
closed #46 
```jsx
const data = await uploadImage(filePath, selectImage);
```
```
```
```
|기능|스크린샷|
```
=> [Feat/#46] 마이페이지 조회 오타수정

src/components/myPageComponent/MyPageContents.jsx, src/pages/MyPage.jsx
```
```
```
```
```
|기능|스크린샷|
```
=> [Feat/#52] 리액트 쿼리 리팩토링

src/utils/getLocalStorageJSON.js
closed #58 
```javascript
export const getLocalStorageJSON = () => {
const localStorageKey = localStorage.key(0);
const localStorageValue = localStorage.getItem(localStorageKey);
const resultObj = JSON.parse(localStorageValue);
return resultObj;
};
```
localStorage의 value 값을 객체 형태로 반환합니다.
- access_token
- email
- id
- avatar
- nickname
등등 console로 출력해보세요
=> [feat/#58] - 로그인한 유저의 정보를 가져오는 로직 추가

src/components/loginPageComponents/LoginInputForm.jsx, src/components/mainPage/MainPageHeader.jsx, src/components/styles/mainPageStyle.js, src/shared/redux/config/configStore.js, src/shared/redux/modules/authSlice.js, src/utils/getLocalStorageJSON.js
- configStore.js
```
const store = configureStore({
reducer: {
test,
user,
area,
auth
}
});
```
=> [feat] - 로그인 상태에 따른 조건부 렌더링 구현

src/components/myPageComponent/MyPageContents.jsx, src/components/myPageComponent/myPageSupabase.js, src/pages/MyPage.jsx
closed #74 
```jsx
if (!storageItem || !uid || !email) {
console.error('유저정보가 존재하지 않습니다. 로그인해주세요.');
alert('유저정보가 존재하지 않습니다. 로그인해주세요.');
// dispatch(logout());
navigate('/login');
}
```
```
```
```
|기능|스크린샷|
```
주석처리 해제해주시고 에러 확인부탁드립니다!
=> [Feat/#74] 마이 페이지 id 에러처리 및 리액트 쿼리로 다시 리팩토링 중

src/components/myPageComponent/MyPageContents.jsx, src/components/myPageComponent/myPageSupabase.js
closed #74 
MyPageContents.jsx
- 위 jsx에서 아래 jsx로 변경
```jsx
const { email, nickname, avatar, uid: id } = userAccount || {};
```
```jsx
const { email, nickname, avatar, uid } = userAccount || {};
```
```
```
```
|기능|스크린샷|
```
=> [Fix/#74]마이 페이지 id 에러처리 및 리액트 쿼리로 다시 리팩토링 중

src/components/myPageComponent/MyPageContents.jsx
closed #78 
- MyPageContents.jsx
```jsx
const { isLoading, isError, data } = useQuery('usersAccounts', readUserAccount, {
onSuccess: (data) => {
const storageItem = getLocalStorageJSON();
const uid = storageItem.user?.id;
const email = storageItem.user?.email;
const nickname = storageItem.user?.user_metadata.nickname;
const avatar = storageItem.user?.user_metadata.avatar;
const userInfo = {
uid,
email,
nickname,
avatar
};
setUserAccount(userInfo);
updateUserAccount({ nickname, avatar });
setThumnailImage(userInfo.avatar);
if (!storageItem || !uid || !email) {
console.error('유저정보가 존재하지 않습니다. 로그인해주세요.');
alert('유저정보가 존재하지 않습니다. 로그인해주세요.');
// dispatch(logout());
navigate('/login');
}
console.log('데이터를 성공적으로 가져왔습니다:', data);
}
});
const { email, nickname, avatar, uid } = userAccount || {}; …
```
=> [Feat,Fix,Bug/#78] - 리액트 쿼리 적용 후 이미지 버그 삼중주 중 이중주 해결

src/components/communityComponents/CommentInputForm.jsx, src/components/communityComponents/CommentList.jsx, src/components/communityComponents/CommunityHeader.jsx, src/components/communityComponents/CommunityInputForm.jsx, src/components/communityComponents/CommunitySupabase.js, src/components/communityComponents/CommunityWriteEditForm.jsx, src/components/communityComponents/WritingList.jsx, src/components/styles/CommunityStyle.js, src/pages/Community.jsx
=> Comunity 유효성 검사 및 css 수정

src/components/loginPageComponents/LoginInputForm.jsx
closed #93 
```javascript
const { error } = await supabase.auth.signUp({
email,
password,
options: {
data: {
nickname,
avatar: defaultProfileImage
}
}
});
```
=> [feat/#93] - 회원가입 시 기본 아바타 적용

src/components/reviewComponents/ReviewForm.jsx, src/components/reviewComponents/ReviewList.jsx, src/components/reviewComponents/ReviewUpdateForm.jsx, src/components/styles/ReviewStyle.jsx
closed #67
```
```
```
```
```
|기능|스크린샷|
```
=> [feat #67] 리뷰 이미지 수정기능 수정 중

src/components/loginPageComponents/LoginInputForm.jsx, src/components/loginPageComponents/loginPageSupabase.js, src/components/mainPage/MainPageHeader.jsx
closed #80 
- 중복 로그인이 아닌 경우, 현재 로그인 하려는 유저의 정보를 DB에 저장
- 로그아웃 클릭 시, 현재 로그인 상태인 유저의 정보를 DB에서 제거
- 유저의 정보를 제거할 때 uid 사용
```
export const removeCurrentLoginUser = async (data) => {
const { error: removeUserError } = await supabase.from('usersAccounts').delete().eq('uid', data);
if (removeUserError) {
return console.log('remove User-Info Error => ', removeUserError);
}
};
```
- [로그아웃] 버튼 클릭 시 동작하는 함수 (메인 페이지 헤더 기준)
```
const handLogOut = async () => {
// 현재 로그인 중인 유저의 정보를 가져옴
const currentLoginUser = await getLoginUserInfo();
// 현재 로그인 중인 유저의 id(=uid)를 가져옴
const { id } = currentLoginUser.user;
// 현재 로그인 상태인 유저 DB에서 현재 유저를 삭제
await removeCurrentLoginUser(id);
dispatch(logout());	    dispatch(logout());
alert('로그아웃 되었습니다');	    alert('로그아웃 되었습니다');
};	  };
```
공통 컴포넌트로 하고자 했으나, 생각보다 어려워서 일단은 메인 …
=> [feat] - 중복 로그인 처리 기능 구현

src/components/myPageComponent/MyPageContents.jsx, src/components/myPageComponent/MyPageHeader.jsx, src/components/myPageComponent/MyPageReviews.jsx, src/components/styles/MyPageContentsStyle.js, src/components/styles/MyPageContentsStyle.jsx, src/components/styles/MyPageHeaderStyle.jsx, src/components/styles/MyPageReviews.js, src/components/styles/MyPageStyle.jsx, src/pages/MyPage.jsx
closed #92
```
```
```
```
```
|기능|스크린샷|
```
=> [Style/#92]MyPage css 완성

src/components/reviewComponents/ReviewForm.jsx, src/components/reviewComponents/ReviewList.jsx, src/components/reviewComponents/ReviewUpdateForm.jsx, src/components/styles/ReviewStyle.jsx, src/pages/ReviewPage.jsx
closed #99 
```
```
```
```
```
|기능|스크린샷|
```
=> [fix #99] 화면 자동 새로고침 구현 완료

src/components/styles/LoginStyle.js
=> [style/#112] - 로그인페이지 로고 이미지 높이 수정

src/components/styles/MyPageReviews.js
```
```
```
```
```
|기능|스크린샷|
```
=> [Chore] 안 쓰는 코드 삭제

src/components/reviewComponents/ReviewForm.jsx, src/components/reviewComponents/ReviewList.jsx, src/pages/ReviewPage.jsx
```
```
```
```
```
|기능|스크린샷|
```
=> [feat] 수정 삭제 조건부 렌더링

src/components/reviewComponents/ReviewForm.jsx, src/components/reviewComponents/ReviewList.jsx, src/components/styles/ReviewStyle.js
closed #109 
```
```
```
```
```
|기능|스크린샷|
```
=> [fix] 리뷰 게시물 정렬 수정

src/components/reviewComponents/ReviewForm.jsx, src/components/reviewComponents/ReviewHeader.jsx, src/components/reviewComponents/ReviewList.jsx, src/components/reviewComponents/ReviewUpdateForm.jsx, src/components/styles/ReviewStyle.js
closed #109 
```
```
```
```
```
|기능|스크린샷|
```
=> [style] 리뷰 페이지 스타일 수정

src/components/reviewComponents/ReviewForm.jsx, src/components/reviewComponents/ReviewList.jsx, src/components/reviewComponents/ReviewUpdateForm.jsx, src/components/reviewComponents/reviewPageSupabase.js, src/pages/ReviewPage.jsx
closed #109 
```
```
```
```
```
|기능|스크린샷|
```
=> [Feat]- 리뷰페이지 코드 리팩토링

src/components/myPageComponent/MyPageHeader.jsx, src/components/styles/MyPageContentsStyle.js, src/components/styles/MyPageHeaderStyle.js
closed #132 
- 헤더에 로고 추가
```
```
```
```
```
|기능|스크린샷|
```
=> [Style/#132] - MyPage 헤더에 로고 추가

src/components/reviewComponents/ReviewList.jsx, src/components/reviewComponents/ReviewUpdateForm.jsx
closed #109 
```
```
```
```
```
|기능|스크린샷|
```
=> [fix] 기본 이미지 오류 수정

src/components/reviewComponents/ReviewUpdateForm.jsx
closed #109 
```
```
```
```
```
|기능|스크린샷|
```
=> [fix] 리뷰 수정페이지 기본 이미지 오류 수정
